### ISSUE TITLE
inline seems to remove whitespace

### ISSUE THREAD

**Issue by jeapostrophe** [wilbowma/scribble-minted#2] opened 2020-06-30 18:59 UTC
I am using the inline version and `@mintinline["javascript"]{const A = B;}` is rendered as `constA=B;` with no spaces. The HTML is

```
<code class="highlight-inline"><span class="kr">const</span> <span class="nx">LHS</span> <span class="o">=</span> <span class="nx">RHS</span><span class="p">;</span></code>
```

I get the behavior I want when I remove `display: inline-table`

**Comment by wilbowma** [comment] 2021-03-29 23:31
What browser are you using? I can't reproduce, but I had another report of a similar issue that seemed browser dependent.

**Comment by wilbowma** [comment] 2021-03-29 23:38
Maybe addressed by 23cfd9d8be60925d56407686b6bc5f5bf18a7eef

**Comment by wilbowma** [comment] 2021-03-30 01:19
Tested in Chromium and Firefox, seems to work.

**Comment by wilbowma** [comment] 2021-03-30 03:03
Also seems to work on iOS safari. Closing.

**Closed as completed by wilbowma** 2021-03-30 03:03 UTC
